export type Account = {
  accountname: string
  phone: string
  cf_775: string
  website: string
  account_no: string
  tickersymbol: string
  fax: string
  account_id: string
  otherphone: string
  employees: number
  email1: string
  ownership: string
  email2: string
  industry: string
  rating: string
  accounttype: string
  emailoptout: boolean
  annual_revenue: number
  annual_revenue_currency_value: number
  assigned_user_id: string
  notify_owner: boolean
  modifiedtime: string
  modifiedby: string
  createdtime: string
  cf_771: string
  isconvertedfromlead: string
  cf_783: string
  primary_twitter: string
  created_user_id: string
  source: string
  last_contacted_on: string
  last_contacted_via: string
  slaid: string
  starred: string
  tags: string
  email_domain: string
  accountstatus: string
  record_currency_id: string
  record_conversion_rate: number
  region: string
  profile_score: number
  profile_rating: string
  emailoptin: string
  emailoptin_requestcount: number
  emailoptin_lastrequestedon: string
  smsoptin: string
  primary_phone_field: string
  primary_email_field: string
  isclosed: boolean
  cf_accounts_licensecounter: number
  siccode: string
  cf_accounts_defaultrealm: string
  sync_to_hubspot: boolean
  cf_accounts_cloudsupport: boolean
  cf_accounts_bowbridgecloudid: string
  bill_country: string
  ship_country: string
  bill_street: string
  ship_street: string
  bill_pobox: string
  ship_pobox: string
  bill_city: string
  ship_city: string
  bill_state: string
  ship_state: string
  bill_code: number
  ship_code: number
  mailing_gps_lat: number
  mailing_gps_lng: number
  cf_accounts_billingemailaddress: string
  description: string
  imagename: string
  id: string
  record_currency_symbol: string
  cf_accounts_logzioaccountid: string
  cf_accounts_logziosubaccounttoken: string
  cf_accounts_apikeycontrol: string
}
