export type Asset = {
  account: string
  contact: string
  cf_assets_contactemail: string
  cf_assets_resellercontact: string
  cf_assets_country: string
  cf_assets_previous: string
  cf_assets_renewedby: string
  cf_assets_realm: string
  product: string
  assetname: string
  cf_assets_features: string
  cf_assets_licensetype: string
  cf_assets_numberofinstances: number
  cf_assets_expirationdate: string
  cf_assets_licenseid: number
  assetstatus: string
  asset_no: string
  serialnumber: string
  assigned_user_id: string
  datesold: string
  created_user_id: string
  modifiedtime: string
  tagnumber: number
  invoiceid: string
  dateinservice: string
  shippingmethod: string
  cf_assets_salesorder: string
  shippingtrackingnumber: number
  source: string
  createdtime: string
  cf_assets_licensebinary: string
  cf_assets_mappings: string
  modifiedby: string
  starred: string
  tags: string
  record_currency_id: string
  record_conversion_rate: string
  isclosed: boolean
  cf_assets_signature: string,
  cf_assets_deployment: string,
  description: string
  id: string
  record_currency_symbol: string | null
}
