export type Case = {
  description: string
  source: string
  starred: string
  tags: string
  record_currency_id: string
  record_conversion_rate: string
  title: string
  casestatus: string
  casepriority: string
  contact_id: string
  parent_id: string
  assigned_user_id: string
  group_id: string
  product_id: string
  age: number
  createdtime: string
  modifiedtime: string
  modifiedby: string
  case_no: string
  wait_count: number
  casechannel: string
  resolution: string
  reassign_count: number
  created_user_id: string
  impact_type: string
  impact_area: string
  resolution_type: string
  deferred_date: string
  customer_reply: string
  reopen_count: number
  from_portal: string
  satisfaction_index: string
  satisfaction_feedback: string
  servicecontract_id: string
  asset_id: string
  cf_cases_s3uploadmeta: string
  cf_cases_private: string
  first_response_expectedon: string
  first_response_actualon: string
  sla_closureon: string
  sla_actual_closureon: string
  last_responded_on: string
  slaid: string
  resolution_time: number
  slastatus: string
  current_state_entry_time: string
  time_spent: string
  first_response_status: string
  is_billable: boolean
  rate: string
  billing_service: string
  is_billed: boolean
  servicetype: string
  servicelocation: string
  work_location: string
  billable_time: number
  total_time: number
  id: string
  isclosed: boolean
  record_currency_symbol: string | null
}
