export type Contact = {
  salutationtype: string
  firstname: string
  lastname: string
  contact_no: string
  phone: string
  mobile: string
  account_id: string
  homephone: string
  otherphone: string
  leadsource: string
  fax: string
  title: string
  cf_contacts_jobttitle: string
  department: string
  birthday: string
  email: string
  contact_id: string
  secondaryemail: string
  assistant: string
  emailoptout: string
  assigned_user_id: string
  assistantphone: string
  notify_owner: string
  donotcall: string
  createdtime: string
  modifiedtime: string
  isconvertedfromlead: boolean
  cf_791: string
  cf_795: string
  modifiedby: string
  source: string
  created_user_id: string
  last_contacted_on: string
  engagement_score: boolean
  slaid: string
  last_contacted_via: string
  primary_twitter: string
  contactstatus: string
  contacttype: string
  profile_score: number
  happiness_rating: string
  referred_by: string
  profile_rating: string
  smsoptin: string
  starred: string
  emailoptin: string
  tags: string
  language: string
  record_currency_id: string
  record_conversion_rate: string
  emailoptin_requestcount: string
  emailoptin_lastrequestedon: string
  primary_phone_field: string
  primary_email_field: string
  isclosed: string
  sync_to_hubspot: string
  cf_777: string
  portal: string
  cf_755: string
  support_start_date: string
  cf_757: string
  support_end_date: string
  cf_759: string
  mailingcountry: string
  othercountry: string
  mailingstreet: string
  otherstreet: string
  mailingpobox: string
  otherpobox: string
  mailingcity: string
  othercity: string
  mailingstate: string
  otherstate: string
  mailingzip: number
  otherzip: number
  mailing_gps_lat: string
  mailing_gps_lng: string
  description: string
  primary_linkedin: string
  followers_linkedin: string
  primary_facebook: string
  followers_facebook: string
  facebookid: string
  instagramid: string
  twitterid: string
  consent_requested: string
  consent_trash_data: string
  consent_lock_data: string
  consent_track_email_engagement: string
  consent_track_shared_documents: string
  consents_last_requested_on: string
  id: string
  record_currency_symbol: string
  cf_contacts_msprole: string
  cf_contacts_mspaccesstocustomer: string
}

