export type Event = {
  subject: string
  description: string
  assigned_user_id: string
  date_start: string
  time_start: string
  due_date: string
  time_end: string
  duration_hours: number
  duration_minutes: number
  eventstatus: string
  sendnotification: boolean
  activitytype: string
  location: string
  createdtime: string
  modifiedtime: string
  taskpriority: string
  notime: number
  visibility: string
  modifiedby: string
  created_user_id: string
  source: string
  starred: string
  tags: string
  record_currency_id: string
  record_conversion_rate: string
  cancellation_reason: string
  allday: boolean
  isclosed: boolean
  invitation_for: string
  meeting_notes: string
  mailing_gps_lat: string
  mailing_gps_lng: string
  conference_link: string
  recording_link: string
  reminder_time: string
  recurringtype: string
  contact_id: string
  parent_id: string
  checkin_datetime: string
  checkout_datetime: string
  checkin_duration: string
  outside_geofence: string
  actual_checkedin_location: string
  geo_fence_violation_distance: string
  id: string
  record_currency_symbol: string | null
}
