export type Potential = {
  potentialname: string
  amount: number
  potential_no: string
  amount_currency_value: number
  related_to: string
  closingdate: string
  opportunity_type: string
  nextstep: string
  leadsource: string
  sales_stage: string
  assigned_user_id: string
  probability: string
  campaignid: string
  createdtime: string
  modifiedtime: string
  modifiedby: string
  forecast_amount: number
  forecast_amount_currency_value: number
  isconvertedfromlead: boolean
  contact_id: string
  cf_773: string
  created_user_id: string
  email: string
  forecast_category: string
  adjusted_amount: number
  adjusted_amount_currency_value: number
  source: string
  last_contacted_on: string
  last_contacted_via: string
  starred: string
  tags: string
  current_stage_entry_time: string
  lost_reason: string
  record_currency_id: string
  record_conversion_rate: string
  pipeline: string
  journey_template_id: string
  next_journey: string
  progress: string
  opp_contactrole: string
  isclosed: boolean
  sync_to_hubspot: string
  prev_sales_stage: string
  description: string
  paidamount: number
  openamount: number
  productid: string
  quantity: number
  listprice: number
  netprice: number
  discount_amount: number
  discount_percent: number
  section_name: string
  section_no: string
  comment: string
  hdnDiscountAmount: number
  hdnDiscountPercent: number
  hdnSubTotal: number
  hdnGrandTotal: number
  pricebook_id: string
  items_sync_with: string
  billing_type: string
  duration: number
  id: string
  record_currency_symbol: string | null
}
