export type Product = {
  productname: string
  productcode: string
  product_no: string
  discontinued: boolean
  manufacturer: string
  productcategory: string
  sales_start_date: string
  sales_end_date: string
  start_date: string
  expiry_date: string
  website: string
  vendor_id: string
  mfr_part_no: string
  vendor_part_no: string
  serial_no: string
  productsheet: string
  glacct: string
  createdtime: string
  modifiedtime: string
  modifiedby: string
  created_user_id: string
  source: string
  starred: string
  tags: string
  record_currency_id: string
  record_conversion_rate: number
  item_barcode: string
  isclosed: boolean
  unit_price: number
  commissionrate: number
  taxclass: string
  purchase_cost: number
  purchase_cost_currency_value: string
  billing_type: string
  usageunit: string
  qty_per_unit: number
  qtyinstock: number
  reorderlevel: number
  assigned_user_id: string
  qtyindemand: number
  defect_qtyinstock: number
  cf_products_features: string
  cf_products_producttype: string
  imagename: string
  description: string
  id: string
  record_currency_symbol: string | null
  product_type: string
  reorder_qty: number
  availablestock: number
  committedstock: number
  incomingstock: number
  cf_products_deployment: string
  tax1: number
  tax5: number
  currency2: number
  currency5: number
  currency6: number
  currency7: number
  currency9: number
}
