export type SalesOrder = {
  subject: string
  potential_id: string
  customerno: string
  salesorder_no: string
  quote_id: string
  vtiger_purchaseorder: string
  contact_id: string
  duedate: string
  carrier: string
  pending: string
  sostatus: string
  salescommission: number
  exciseduty: number
  hdnGrandTotal: number
  hdnSubTotal: number
  hdnTaxType: string
  account_id: string
  assigned_user_id: string
  createdtime: string
  modifiedtime: string
  currency_id: string
  conversion_rate: number
  modifiedby: string
  pre_tax_total: number
  created_user_id: string
  source: string
  starred: string
  tags: string
  record_currency_id: string
  record_conversion_rate: number
  isclosed: boolean
  enable_recurring: boolean
  recurring_frequency: string
  start_period: string
  end_period: string
  payment_duration: number
  invoicestatus: string
  bill_country: string
  ship_country: string
  bill_street: string
  ship_street: string
  bill_pobox: string
  ship_pobox: string
  bill_city: string
  ship_city: string
  bill_state: string
  ship_state: string
  bill_code: string
  ship_code: string
  terms_conditions: string
  productid: string
  quantity: number
  listprice: number
  comment: string
  hdnDiscountAmount: number
  hdnDiscountPercent: number
  tax1: number
  tax2: number
  tax3: number
  hdnS_H_Percent: number
  tax4: number
  txtAdjustment: number
  hdnS_H_Amount: number
  image: string
  purchase_cost: number
  margin: number
  region_id: string
  netprice: number
  pricebook_id: string
  section_no: string
  section_name: string
  margin_percentage: number
  delivered_qty: number
  outstanding_qty: number
  markup_percentage: number
  purchase_cost_total: number
  margin_total: number
  margin_percentage_total: number
  markup_percentage_total: number
  billing_type: string
  duration: number
  unit_purchase_cost: number
  description: number
  cf_785: string
  paidamount: number
  openamount: number
  id: string
  record_currency_symbol: string | null
}
