export type User = {
  user_name: string
  user_type: string
  roleid: string
  reports_to_id: string
  user_primary_group: string
  user_password: string
  confirm_password: string
  language: string
  is_admin: string
  status: string
  lead_view: string
  end_hour: string
  accesskey: string
  first_name: string
  dayoftheweek: string
  last_name: string
  start_hour: string
  title: string
  date_format: string
  hour_format: string
  department: string
  email1: string
  time_zone: string
  activity_view: string
  secondaryemail: string
  email2: string
  callduration: string
  phone_home: string
  othereventduration: string
  phone_work: string
  defaulteventstatus: string
  phone_mobile: string
  defaultactivitytype: string
  phone_other: string
  reminder_interval: string
  phone_fax: string
  calendarsharedtype: string
  defaultcalendarview: string
  description: string
  taskduration: string
  theme: string
  rowheight: string
  learning_score: string
  userlabel: string
  address_street: string
  address_city: string
  address_state: string
  address_country: string
  address_postalcode: string
  currency_id: string
  display_preference_currency: string
  currency_grouping_pattern: string
  currency_decimal_separator: string
  currency_grouping_separator: string
  currency_symbol_placement: string
  no_of_currency_decimals: string
  truncate_trailing_zeros: string
  currency_format: string
  number_format: string
  asterisk_extension: string
  use_asterisk: string
  plivo_extension: string
  twilio_extension: string
  vicidial_extension: string
  exotel_extension: string
  telzio_extension: string
  knowlarity_extension: string
  plivo_auth: string
  business_hours: string
  defaultlandingpage: string
  collapsemodulemenu: string
  default_record_view: string
  leftpanelhide: string
  internal_mailer: string
  layout: string
  darkmode: string
  display_name_format: string
  imagename: string
  signature: string
  signature_before_quoted_text: string
  id: string
}
