export type VTCMRealm = {
  assigned_user_id: string;
  cf_vtcmrealms_authenticationdomain: string;
  cf_vtcmrealms_configurations: string;
  cf_vtcmrealms_defaultrealmof: string;
  cf_vtcmrealms_deployment: string;
  cf_vtcmrealms_description: string;
  cf_vtcmrealms_ldapdn: string;
  cf_vtcmrealms_ldapuserpassword: string;
  cf_vtcmrealms_oldauthenticationdomain: string;
  cf_vtcmrealms_organization: string;
  cf_vtcmrealms_provider: string;
  cf_vtcmrealms_status: string;
  created_user_id: string;
  createdtime: string;
  fld_realmid: string;
  fld_vtcmrealmsname: string;
  id: string;
  isclosed: string;
  modifiedby: string;
  modifiedtime: string;
  record_conversion_rate: string;
  record_currency_id: string;
  record_currency_symbol: string | null;
  source: string;
  starred: string;
  tags: string;
  vtcmrealmsnumber: string;
};
