export type VTCMScanCluster = {
  assigned_user_id: string;
  cf_vtcmscanclusters_authenticationdomains: string;
  cf_vtcmscanclusters_eventsurl: string;
  cf_vtcmscanclusters_owner: string;
  cf_vtcmscanclusters_status: string;
  created_user_id: string;
  createdtime: string;
  fld_accessurl: string;
  fld_awsregion_2769: string;
  fld_azurergion_2771: string;
  fld_googlecloudregion_2773: string;
  fld_numberofscanners: string;
  fld_provider_2767: string;
  fld_type_2761: string;
  fld_vtcmscanclustersname: string;
  id: string;
  isclosed: string;
  modifiedtime: string;
  modifiedby: string;
  record_conversion_rate: string;
  record_currency_id: string;
  record_currency_symbol: string | null;
  source: string;
  starred: string;
  tags: string;
  vtcmscanclustersnumber: string;
};
