export type VTCMSid = {
  assigned_user_id: string;
  cf_vtcmsids_configurations: string;
  cf_vtcmsids_configurationdifference: string;
  cf_vtcmsids_description: string;
  cf_vtcmsids_organization: string;
  cf_vtcmsids_realm: string;
  created_user_id: string;
  createdtime: string;
  fld_vtcmsidsname: string;
  id: string;
  isclosed: string;
  modifiedby: string;
  modifiedtime: string;
  record_conversion_rate: string;
  record_currency_id: string;
  record_currency_symbol: string | null;
  source: string;
  starred: string;
  tags: string;
  vtcmsidsnumber: string;
};
