export type PurchaseOrder = {
  subject: string
  purchaseorder_no: string
  vendor_id: string
  requisition_no: string
  tracking_no: string
  contact_id: string
  duedate: string
  carrier: string
  salescommission: string
  exciseduty: string
  hdnGrandTotal: number
  hdnSubTotal: number
  hdnTaxType: string
  postatus: string
  assigned_user_id: string
  createdtime: string
  modifiedtime: string
  currency_id: string
  conversion_rate: number
  modifiedby: string
  pre_tax_total: number
  paid: number
  balance: number
  created_user_id: string
  accountid: string
  source: string
  starred: string
  tags: string
  salesorder_id: string
  record_currency_id: string
  record_conversion_rate: number
  isclosed: boolean
  cf_799: string
  bill_country: string
  ship_country: string
  bill_street: string
  ship_street: string
  bill_pobox: string
  ship_pobox: string
  bill_city: string
  ship_city: string
  bill_state: string
  ship_state: string
  bill_code: string
  ship_code: string
  productid: string
  quantity: number
  listprice: number
  comment: string
  hdnDiscountAmount: number
  hdnDiscountPercent: number
  tax1: number
  tax2: number
  tax3: number
  txtAdjustment: number
  hdnS_H_Percent: number
  tax4: number
  hdnS_H_Amount: number
  image: string
  region_id: string
  netprice: number
  section_no: string
  section_name: string
  received_qty: number
  outstanding_qty: number
  billing_type: string
  duration: number
  description: string
  paidamount: number
  openamount: number
  id: string
  record_currency_symbol: string | number
}
